/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * 
 * @author Antonio Sanchez Espinosa
 * 
 * Clase que ejecuta el FXML para obtener una ventana gráfica.
 *
 */
public class Main extends Application {

	@Override
	public void start(Stage stage) throws Exception {
		Parent root = FXMLLoader.load(getClass().getResource("viewsandcontrollers/calculadora/Calculadora.fxml"));
		Scene scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}

	/**
	 * Ejecuta el FXML
	 * @param args introducidos mediante linea de consola
	 */
	public static void main(String[] args) {
		launch();
	}
}
